apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-30-jenkins
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: student-30
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      targetRevision: 12.4.0
      helm:
        valueFiles:
          - $values/jenkins/values.yaml
      chart: jenkins
    - repoURL: 'https://github.com/JKrag/argocd-training.git'
      targetRevision: main
      ref: values
